language: minimal

script:
- docker build -t isaqb-adoc2pdf --force-rm adoc2pdf/
- ./adoc2pdf/adoc2pdf.sh ${PWD}/docs/advanced-curriculum.adoc DE prod
- ./adoc2pdf/adoc2pdf.sh ${PWD}/docs/advanced-curriculum.adoc EN prod

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "build/advanced-curriculum_DE_prod.pdf"
    - "build/advanced-curriculum_EN_prod.pdf"
  skip_cleanup: true
  draft: true
  overwrite: true
